config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#index'
  
  get 'pages/index'

  resources :tests, path: '/tests', only: [:index, :show], category_slug: 'tests'

  post 'tests/:id/questions', to: 'questions#answer', as: :question_answer
  get 'tests/:id/questions/:question_id', to: 'questions#show', as: :question_ask
  #post 'tests/:id/questions/:question_id', to: 'questions#answer', as: :question_answer

  get 'pages/finish', as: :finish
  
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord

	has_many :answers
	
	mount_uploader :image, ImagesUploader
	
	scope :n_random, -> (n){ order("RANDOM()").limit(n)}
end

app/models/test.rb
class Test < ApplicationRecord
	has_many :questions
	#has_many :answers, through: :questions
	
	scope :ordered, -> { order :id }

	def questions_count
		return 0 unless self.N.present?
		self.N
	end
end

app/models/test_passing.rb
class TestPassing < ApplicationRecord
	belongs_to :test
	
	before_create do
		test_N = Test.find(self.test_id).questions_count
		
		self.enum_questions = Question.n_random(test_N).ids 
		
		self.current_state = 0
	end
	
	before_save do
		self.current_state += 1 unless self.current_state.nil?
	end
	

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
    def admin?
        self.admin
     end         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def finish
  if session[:test_id].nil?
  redirect_to root_path
  return
  end
  
  passing = TestPassing.find(session[:test_id])
  @true_count = passing.user_results.find_all{ |elem| elem == 1 }.size
  @persent_count = percent_of(@true_count, passing.enum_questions.size)

  UserMailer.with(email: user_signed_in? ? current_user.email : "", passing: passing).testpass_email.deliver_now if user_signed_in?

  session.clear
  end
  
  private 
  
  def percent_of(m, n)
    m.to_f / n.to_f * 100.0
  end
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
  end
  
  def show
    @passing = TestPassing.find(session[:test_id])
 
	@question = Question.find_by_id(@passing.enum_questions[@passing.current_state])
	@answers = @question.answers unless @question.nil?

  end
  
  def answer
   #abort is_right?.inspect
   @passing = TestPassing.find(session[:test_id])
   @passing.update user_answers:@passing.user_answers.to_a+params[:answers].to_a,user_results:@passing.user_results.to_a + (is_right? ? [1] : [0])

    if @passing.enum_questions[@passing.current_state].nil?
		redirect_to :finish
		return
	else
		redirect_to question_ask_path(@passing.test.id,@passing.enum_questions[@passing.current_state] )
    end 
   
  end
  
  private
  
  def is_right?
  if params[:answers].nil?
	return false
  end
  
    question = Question.find(@passing.enum_questions[@passing.current_state])

	(question.answer_true_ids - params[:answers].map(&:to_i)).empty? && (question.answer_true_ids.length == params[:answers].length)
  end
  
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def index
	 @tests = Test.ordered
  end
  
  def show
	@test = Test.find_by_id params[:id]
	passing = TestPassing.create user_id:user_signed_in? ? current_user.id : 0, test_id:params[:id]
	@question = @test.questions.find(passing.enum_questions[passing.current_state])
	session[:test_id] = passing.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="text-center"  data-turbolinks="false">

    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <header class="masthead mb-auto">
        <div class="inner">
          <h3 class="masthead-brand">My test-task</h3>
          <nav class="nav nav-masthead justify-content-center">

            <% if user_signed_in? %>
				<%= link_to "Logout", destroy_user_session_path, :method => :delete , class:"nav-link"%>
			<% else %>
				<%=link_to 'Register', new_user_registration_path, class:"nav-link active" %>
				<%=link_to 'Login', new_user_session_path, class:"nav-link " %>
			<% end %>
          </nav>
        </div>
      </header>

      <main role="main" class="inner cover">
        	<p class="lead notice"><%= notice %></p>
		<p class="lead alert"><%= alert %></p>
        <%= yield %>
      </main>

      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
        </div>
      </footer>
    </div>

  </body>
</html>

app/views/pages/finish.html.erb
<h1>Test is done!</h1>
<p>All is good!</p>
<p>You result is <%= @true_count %></p>
<p>Pecent is <%= sprintf("%.2f", @persent_count) %>% </p>
<p><%= link_to 'Test it again!', root_path %></p>

app/views/pages/index.html.erb
<h1>Testing users</h1>
<p>light testing</p>
<p>Hello, all</p>

app/views/questions/index.html.erb
<h1>Go to test yourself!</h1>
<p>light testing!! All is good!</p>
<p><%= link_to 'Test it!', tests_path %></p>

app/views/questions/show.html.erb
<h1>Questions of a test !</h1>
<p>Get answer!</p>

<% unless @question.nil?%>
<%= form_for @question, url: question_answer_path(@passing.test.id), method: "post" do |f| %>

  <%= f.text_field :title %><br>
  <%= f.text_field :txt %><br>
  <br>
  
  
  <h2>Get write answer:</h2>
  <% unless @answers.nil?%>
   <ul>
<% @answers.each do |answer| %>
 
   <li><%= check_box_tag 'answers[]', answer.id %> <%= :txt %></li>
  
<% end %>
</ul>
<% end %>
  <%= f.submit "Next" %>
<% end %>
<% end %>